spring.application.name=api

# Habilita la consola visual de la base de datos
spring.h2.console.enabled=true
# La URL para conectar (puedes poner el nombre que quieras)
spring.datasource.url=jdbc:h2:mem:ecotrackdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Esto hace que veamos las consultas SQL en la consola de IntelliJ
spring.jpa.show-sql=true
